version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres

    ports:
      - 8000:8000
    # syn changes in container with local dir  
    volumes:
      - ./:/usr/src/app

    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=bookmarks_api
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60

    command: alembic upgrade head
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookmarks_api
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

# docker-compose run api alembic upgrade head